apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgroles-monitoring
resources:
  - resources.yaml
configMapGenerator:
  - name: pgroles-policy-state
    files: [custom-resource-state.yaml]
  - name: pgroles-collector
    files: [collector.yaml]
