// Generated by docs/scripts/generate-manifest-types.mjs. Do not edit.

export type ManifestMetadataSchemaVersion = "pgroles.manifest-metadata.v1"

export type AuthProvider = { "project"?: string | null; "type": "cloud_sql_iam" } | { "cluster"?: string | null; "project"?: string | null; "type": "alloydb_iam" } | { "region"?: string | null; "type": "rds_iam" } | { "tenant_id"?: string | null; "type": "azure_ad" } | { "project_ref"?: string | null; "type": "supabase" } | { "organization"?: string | null; "type": "planet_scale" }
export type ConfigValue = string
export type DefaultPrivilege = { "grant": Array<DefaultPrivilegeGrant>; "owner"?: string | null; "schema"?: string | null; "scope"?: DefaultPrivilegeScopeSpec | null }
export type DefaultPrivilegeGrant = { "ensure"?: Ensure; "on_type": ObjectType; "privileges": Array<Privilege>; "role"?: string | null }
export type DefaultPrivilegeScopeSpec = { "schema"?: string | null; "type": DefaultPrivilegeScopeType }
export type DefaultPrivilegeScopeType = "global" | "schema"
export type Ensure = "present" | "absent"
export type Grant = { "ensure"?: Ensure; "object": ObjectTarget; "privileges": Array<Privilege>; "role": string }
export type MemberSpec = { "admin"?: boolean | null; "inherit"?: boolean | null; "name": string }
export type Membership = { "exclusive"?: boolean; "members": Array<MemberSpec>; "role": string }
export type ObjectTarget = { "name"?: string | null; "schema"?: string | null; "type": ObjectType }
export type ObjectType = "table" | "view" | "materialized_view" | "sequence" | "function" | "schema" | "database" | "type"
export type PasswordSource = { "from_env": string }
export type Privilege = "SELECT" | "INSERT" | "UPDATE" | "DELETE" | "TRUNCATE" | "REFERENCES" | "TRIGGER" | "EXECUTE" | "USAGE" | "CREATE" | "CONNECT" | "TEMPORARY"
export type Profile = { "config"?: {  } & Record<string, ConfigValue>; "default_privileges"?: Array<DefaultPrivilegeGrant>; "grants"?: Array<ProfileGrant>; "inherit"?: boolean | null; "login"?: boolean | null }
export type ProfileGrant = { "ensure"?: Ensure; "object": ProfileObjectTarget; "privileges": Array<Privilege> }
export type ProfileObjectTarget = { "name"?: string | null; "type": ObjectType }
export type RoleDefinition = { "bypassrls"?: boolean | null; "comment"?: string | null; "config"?: {  } & Record<string, ConfigValue>; "connection_limit"?: number | null; "createdb"?: boolean | null; "createrole"?: boolean | null; "external"?: boolean; "inherit"?: boolean | null; "login"?: boolean | null; "name": string; "password"?: PasswordSource | null; "password_valid_until"?: string | null; "preserve_undeclared_grants"?: boolean; "replication"?: boolean | null; "superuser"?: boolean | null }
export type RoleRetirement = { "drop_owned"?: boolean; "reassign_owned_to"?: string | null; "role": string; "terminate_sessions"?: boolean }
export type SchemaBinding = { "name": string; "owner"?: string | null; "profiles"?: Array<string>; "role_pattern"?: string | null }
export type PolicyManifest = { "auth_providers"?: Array<AuthProvider>; "default_owner"?: string | null; "default_privileges"?: Array<DefaultPrivilege>; "grants"?: Array<Grant>; "memberships"?: Array<Membership>; "profiles"?: {  } & Record<string, Profile>; "retirements"?: Array<RoleRetirement>; "role_pattern"?: string | null; "roles"?: Array<RoleDefinition>; "schemas"?: Array<SchemaBinding> }

export namespace CompileResponseSchema {
export type AuthProvider = { "project": string | null; "type": "cloud_sql_iam" } | { "cluster": string | null; "project": string | null; "type": "alloydb_iam" } | { "region": string | null; "type": "rds_iam" } | { "tenant_id": string | null; "type": "azure_ad" } | { "project_ref": string | null; "type": "supabase" } | { "organization": string | null; "type": "planet_scale" }
export type CompiledDefaultPrivilege = { "ensure": Ensure; "grantee": string; "on_type": ObjectType; "owner": string; "privileges": Array<Privilege>; "scope": CompiledDefaultPrivilegeScope }
export type CompiledDefaultPrivilegeScope = { "type": "global" } | { "schema": string; "type": "schema" }
export type CompiledExpandedPolicy = { "default_privileges": Array<CompiledDefaultPrivilege>; "grants": Array<CompiledGrant>; "memberships": Array<CompiledMembership>; "roles": Array<CompiledRole>; "schemas": Array<CompiledSchema> }
export type CompiledGrant = { "ensure": Ensure; "name": string | null; "object_type": ObjectType; "privileges": Array<Privilege>; "role": string; "schema": string | null }
export type CompiledMembership = { "admin": boolean; "exclusive": boolean; "inherit": boolean; "member": string; "role": string }
export type CompiledPolicy = { "desired": CompiledRoleGraph; "expanded": CompiledExpandedPolicy; "manifest": PolicyManifest }
export type CompiledRole = { "bypassrls": boolean | null; "comment": string | null; "config": {  } & Record<string, string>; "connection_limit": number | null; "createdb": boolean | null; "createrole": boolean | null; "external": boolean; "inherit": boolean | null; "login": boolean | null; "name": string; "password": PasswordSource | null; "password_valid_until": string | null; "preserve_undeclared_grants": boolean; "replication": boolean | null; "superuser": boolean | null }
export type CompiledRoleGraph = { "default_privilege_absences": Array<DesiredDefaultPrivilege>; "default_privileges": Array<DesiredDefaultPrivilege>; "exclusive_membership_roles": Array<string>; "grant_absences": Array<DesiredGrant>; "grants": Array<DesiredGrant>; "memberships": Array<CompiledMembership>; "roles": Array<DesiredRole>; "schemas": Array<DesiredSchema> }
export type CompiledSchema = { "name": string; "owner": string | null }
export type ConfigValue = string
export type DefaultPrivilege = { "grant": Array<DefaultPrivilegeGrant>; "owner"?: string | null; "schema"?: string | null; "scope"?: DefaultPrivilegeScopeSpec | null }
export type DefaultPrivilegeGrant = { "ensure"?: Ensure; "on_type": ObjectType; "privileges": Array<Privilege>; "role"?: string | null }
export type DefaultPrivilegeScopeSpec = { "schema"?: string | null; "type": DefaultPrivilegeScopeType }
export type DefaultPrivilegeScopeType = "global" | "schema"
export type DesiredDefaultPrivilege = { "grantee": string; "on_type": ObjectType; "owner": string; "privileges": Array<Privilege>; "scope": CompiledDefaultPrivilegeScope }
export type DesiredGrant = { "name": string | null; "object_type": ObjectType; "privileges": Array<Privilege>; "role": string; "schema": string | null }
export type DesiredRole = { "bypassrls": boolean; "comment": string | null; "config": {  } & Record<string, string>; "connection_limit": number; "createdb": boolean; "createrole": boolean; "inherit": boolean; "login": boolean; "name": string; "password_valid_until": string | null; "replication": boolean; "superuser": boolean }
export type DesiredSchema = { "name": string; "owner": string | null; "owner_privileges": Array<Privilege> }
export type DiagnosticSeverity = "error" | "warning" | "info"
export type Ensure = "present" | "absent"
export type Grant = { "ensure"?: Ensure; "object": ObjectTarget; "privileges": Array<Privilege>; "role": string }
export type MemberSpec = { "admin"?: boolean | null; "inherit"?: boolean | null; "name": string }
export type Membership = { "exclusive"?: boolean; "members": Array<MemberSpec>; "role": string }
export type ObjectTarget = { "name"?: string | null; "schema"?: string | null; "type": ObjectType }
export type ObjectType = "table" | "view" | "materialized_view" | "sequence" | "function" | "schema" | "database" | "type"
export type PasswordSource = { "from_env": string }
export type PolicyDiagnostic = { "code": string; "message": string; "path"?: string | null; "range"?: SourceRange | null; "severity": DiagnosticSeverity }
export type PolicyManifest = { "auth_providers": Array<AuthProvider>; "default_owner"?: string | null; "default_privileges": Array<DefaultPrivilege>; "grants": Array<Grant>; "memberships": Array<Membership>; "profiles": {  } & Record<string, Profile>; "retirements": Array<RoleRetirement>; "role_pattern"?: string | null; "roles": Array<RoleDefinition>; "schemas": Array<SchemaBinding> }
export type Privilege = "SELECT" | "INSERT" | "UPDATE" | "DELETE" | "TRUNCATE" | "REFERENCES" | "TRIGGER" | "EXECUTE" | "USAGE" | "CREATE" | "CONNECT" | "TEMPORARY"
export type Profile = { "config"?: {  } & Record<string, ConfigValue>; "default_privileges": Array<DefaultPrivilegeGrant>; "grants": Array<ProfileGrant>; "inherit": boolean | null; "login": boolean | null }
export type ProfileGrant = { "ensure"?: Ensure; "object": ProfileObjectTarget; "privileges": Array<Privilege> }
export type ProfileObjectTarget = { "name": string | null; "type": ObjectType }
export type RoleDefinition = { "bypassrls"?: boolean | null; "comment"?: string | null; "config"?: {  } & Record<string, ConfigValue>; "connection_limit"?: number | null; "createdb"?: boolean | null; "createrole"?: boolean | null; "external"?: boolean; "inherit"?: boolean | null; "login"?: boolean | null; "name": string; "password"?: PasswordSource | null; "password_valid_until"?: string | null; "preserve_undeclared_grants"?: boolean; "replication"?: boolean | null; "superuser"?: boolean | null }
export type RoleRetirement = { "drop_owned": boolean; "reassign_owned_to": string | null; "role": string; "terminate_sessions": boolean }
export type SchemaBinding = { "name": string; "owner": string | null; "profiles": Array<string>; "role_pattern"?: string | null }
export type SourceRange = { "endByte": number; "startByte": number }
export type Value = { "diagnostics": Array<PolicyDiagnostic>; "policy"?: CompiledPolicy | null; "schema_version": string }

}
export type CompileResponse = CompileResponseSchema.Value

export namespace PolicyDiagnosticSchema {
export type DiagnosticSeverity = "error" | "warning" | "info"
export type SourceRange = { "endByte": number; "startByte": number }
export type Value = { "code": string; "message": string; "path"?: string | null; "range"?: SourceRange | null; "severity": DiagnosticSeverity }

}
export type PolicyDiagnostic = PolicyDiagnosticSchema.Value

export namespace PolicyRequestSchema {
export type Value = { "desired_yaml": string; "schema_version": string }

}
export type PolicyRequest = PolicyRequestSchema.Value

export namespace ValidateResponseSchema {
export type DiagnosticSeverity = "error" | "warning" | "info"
export type PolicyDiagnostic = { "code": string; "message": string; "path"?: string | null; "range"?: SourceRange | null; "severity": DiagnosticSeverity }
export type SourceRange = { "endByte": number; "startByte": number }
export type Value = { "diagnostics": Array<PolicyDiagnostic>; "schema_version": string; "valid": boolean }

}
export type ValidateResponse = ValidateResponseSchema.Value

export interface PolicyAuthoringEngine {
  validate(input: PolicyRequest): ValidateResponse
  compile(input: PolicyRequest): CompileResponse
}
